### PR TITLE
Features/send password reset email

### PR DESCRIPTION
**Pull request by npauzenga**
Hey @Enriikke check out specs for `SendPasswordResetEmail` and `UserMailer.password_reset`.

As it stands I'm not guarding the `password_reset` method against a missing reset token. The interactor will fail if there isn't one but if I want to use the mailer on it's own (for some reason), should it have a guard clause that checks the user's `reset_token`?

### CODE REVIEW

**Comment by enriikke** [comment]
Looks great @npauzenga!!! :steam_locomotive: :elephant: :electric_plug: 

I think it's reasonable that the mailer doesn't guard against a missing token. You could do that if you wanted to though. The good thing is that if the token is missing the mailer wouldn't fail since it would just render the email without the token. That could be confusing for the user but the application wouldn't crash. If we keep track of the app and we know that the mailer will always be called through the interactor then we should be good. But if you wanted to use it without the interactor then having a guard clause wouldn't hurt.

**Comment by npauzenga** [comment]
Hey @Enriikke! Updated with green specs.

One thing --

I don't have a test for `deliver_now` failing. I think that's probably ok but I AM test that the interactor sends an email. Perhaps this isn't the right spot for that kind of test. The Interactor should really just be responsible for calling `UserMailer.password_reset` and the rest is handled by `password_reset`.

...but then I'm not testing if the email was sent in any spec.

**Comment by enriikke** [comment]
I think this comes around a bit to what we learned about the interactors. You do have a test that validates that an email was sent:

``` ruby
it "sends an email" do
  send_email
  expect(ActionMailer::Base.deliveries.count).to eq(1)
end
```

I think that should be sufficient, and we can rely on ActionMailer to work as advertised (and that hopefully they are doing their own tests). What do you think? We can also look more into feature specs.

**Comment by npauzenga** [comment]
Yup, sorry, my comment was a little circular :confused: 

I do have the `sends an email` spec for the interactor but maybe I shouldn't. The Interactor doesn't send an email -- `deliver_now` (and `password_reset`) does. Maybe we test that the Interactor calls `send_reset_email` when successful, and that `password_reset` assigns the correct info and is given the correct argument. Then leave it that -- no check to see if an email was sent.

Testing strategies are fun! I think Thoughtbot has a Rails-specific book on TDD that I'm gonna try.

**Pull request merged**
